---
ID: "f7b62cac-4293-4c1b-a560-123c9d0c4181"
Parent: "611a2718-6ad8-4ae4-be83-15fa8cd8d046"
Template: "1c82e550-ebcd-4e5d-8abd-d50d0809541e"
Path: /sitecore/content/Skate Park/Skate Park/Home/Inventory/Data
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230824T185149Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Andy Kojs
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Andy Kojs
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1a3e83cf-cc31-4ac8-84a0-8f3e67b62f15"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Andy Kojs
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230824T185149Z
